### ISSUE TITLE
Add "Skills" As An Option for Match

### ISSUE THREAD

**Issue by brenapp** [brenapp/referee.fyi#107]
Currently, the match dialog allows referees to enter "non-match", which is intended for skills and inspection notes, or generally anything that doesn't correspond to a match. 

We should add a "skills" match that can be selected.  This would allow a HR to designate an entry as happening during a skills match. Whether we should allow them to specify which run type and which attempt (i.e. skills Prog 1), or just have a generic match type of skills, I'm not sure.

Entries with type skills should not be visible from the match dialog.

**Comment by Ali-Is-He** [comment]
What problem is this trying to solve? Is this trying to solve a "the label is incorrect" problem or a "we should not show skills violations with match violations" problem?
Having information about the type of skills run might be nice. But not sure what use case would need to know the specific skills run during which the violation was committed.

I think if you want to have all the violations in 1 view (i.e have skills violations and match violations both appear when you tap on a team number for a specific match) then you should color code the skills as blue or some other color so the ref knows to not look at those for escalation purposes.

Is it possible to have like the match tab only show match related violations and the team tab show all violations for a specific team and then just have skills be a separate division that has a separate list of violations?

**Comment by brenapp** [comment]
I'm thinking in two parts here:

1) We should have a way for referees to designate entries as "skills-related" apart from being non-match, which is necessary so that

2) Violations recorded in skills matches (i.e., SG6 DQ) are not shown the same in the match dialog. What's most important is that they're not shown in the summary; I'm not sure how much it matters if they are shown in the list of incidents

The intention here is something like this example: a team has only had an SG6 DQ once in skills, and they are being listed as DQ'd for SG6. In a match context, the referee is not thinking of skills. In the match summary here, there is no distinction between an SG6 DQ in a match and an SG6 DQ in skills, even though that has very different implications here

<img width="789" alt="Screenshot 2024-05-03 at 22 09 34" src="https://github.com/brenapp/referee.fyi/assets/8839926/d043ca81-757a-43b1-a30c-5c9ef03296b4">


Now that I'm thinking about it more, I think an approach like this would be best:
1. Allow users to specify "Skills" as a match type. We don't really care about which round it was
2. Don't display those Skills DQs in the team summary on the match dialog, but probably still show that entry when the user expands the team in the match dialog.

**Comment by Ali-Is-He** [comment]
I agree that skills violations should be separated from match violations to avoid confusion from different contexts and agree that the simplest way might be to just mark the violation as happening during a skills match and to have a "ignore skills" filter on violations shown in the match view but not have any filters on the team view.

**Comment by brenapp** [comment]
So, the current [data model](https://github.com/brenapp/referee.fyi/blob/4065391b73124695f823fe8ec85367917ce33012/worker/types/EventIncidents.d.ts#L21) for a entry is:

```typescript
export type Incident = {
  id: string;

  time: Date;

  event: string; // SKU
  division: number; // division ID

  match?: {
    name: string;
    id: number;
  };
  team?: string; // team number

  revision?: {
    count number;
    user: WebSocketSender;
    history: ChangeLog[];
  };

  outcome: IncidentOutcome;
  rules: string[];
  notes: string;
};

```

I think we may be able to solve multiple problems at once here. Having non-match (inspection + skills) entries defaulting to division 1 at worlds caused some problems for our analytics. Instead, we could create alternative division sentinels to better represent these non-match entries.

**Comment by Ali-Is-He** [comment]
not sure if I know what a "division sentinel" is but if the idea is to create a separate division that is skills then I think I can see that working well and just letting the general notes be non match submissions

**Comment by brenapp** [comment]
The foundations for this has been created in `feat/migrations`, including migration infrastructure and a "skills" match type.

**Comment by brenapp** [comment]
Closing as this has been merged to main
