### ISSUE TITLE
What's Changed Dialog

### ISSUE THREAD

**Issue by brenapp** [brenapp/referee.fyi#16]
When we push updates to the app, it may be helpful to have a "what's changed" dialog appear for users. However, there are some caveats to make sure it does not hurt usability:

1. It should only appear on subsequent visits, i.e., you should never see it the first time you visit.

2. Very quick to dismiss. We can llow users to see it again somewhere in the UI if they missed it.

When the app starts, we should download a change log data file from the server. Compare the current version of the app against the version, and if the stored version is not equal to the current version, display the what's changed dialog with all the updates since the user last opened the app. If there is no value stored, we should assume this is a new user, and not display the dialog.

At the end, store the current version of the app, so that it can be used for the future.

**Comment by MiniMitre** [comment]
Will be working on this, along with a 'tutorial' for the first time the user loads up the page (with option to replay the tutorial at any time to train new users)
