### ISSUE TITLE
Keep New Report Page Open when Submitting an Improper Violation

### ISSUE THREAD

**Issue by DaleNaci** [brenapp/referee.fyi#23]
On the "New Report" page, upon clicking the Submit button, the page closes. I believe that it should stay open.

To replicate:

1. Go to referee.fyi
2. Select "New Entry" button
3. Click Submit

**Comment by DaleNaci** [comment]
Alternatively, the Submit button can just be disabled if the form has not been properly filled out.

**Comment by brenapp** [comment]
From a usability perspective, I think we could go either way. The general user experience I am primarily thinking about when developing this app is:

1. Head Referee goes from match-to-match, and reports violations in the match
2. There's generally 0 to 1 violations in a match, with some exceptional matches generating 2 or 3. 

From this, I think we should optimize for the experience where a user only needs to enter 1 violation for a match (i.e. the dialog closing, current behavior). I'm totally open to changing my mind if this is not how people are using the app, however.

**Comment by brenapp** [comment]
Closing as will not be done - I think for most workflows, closing it is the better approach
