### ISSUE TITLE
Allow editing of violations

### ISSUE THREAD

**Issue by MiniMitre** [brenapp/referee.fyi#29]
Once a user has submitted a violation, allow them to edit it afterwards.

Expected implementation will allow a violation to be edited anywhere it can be viewed.

**Comment by brenapp** [comment]
I am thinking there should be a separate editing dialog, for a couple reasons: 
- Currently, the logic to pick a match and team has become quite monstrous, depending on if there are multiple divisions. Simplifying logic to preserving the team and allowing users to change match permits us to not need to modify indexes, while also simplifying the UI.
- We probably only want to allow the user to edit specific fields, i.e match, outcome, notes, rules citations.

**Comment by brenapp** [comment]
Implemented in #70 !
