### ISSUE TITLE
View Incidents by rule number instead of by match

### ISSUE THREAD

**Issue by MiniMitre** [brenapp/referee.fyi#43]
When the head referee is determining whether a minor violation should escalate to a major violation, they will want to know how many times a team has violated a certain rule (and in what matches).

Undecided on how this will be implemented. But perhaps an option to view the 'incidents' for each team in a table view. With a different rule number on each row (as this list could get quite long), and a column for 'minor violations' and a column for 'major violations'. In each cell it will say the match number that the team violated the rule.

**Comment by brenapp** [comment]
Fixed by #49
