### ISSUE TITLE
How to properly deal with violations in practise matches

### ISSUE THREAD

**Issue by MiniMitre** [brenapp/referee.fyi#44]
We would like to allow referees to record violations in practise matches, as they are practise for the referees as well, but those violations should not count towards 'repeated violations escalate to a major violation', as it is just a practise for the team (and we want to make sure teams turn up for practise matches without worrying about accumulating violations).

Some simple way to indicate that the team did commit the violation in practise but it doesn't matter for escalations (as it can be easy to miss the 'P' instead of the 'Q' when checking when violations happened. Related to #43

**Comment by brenapp** [comment]
This is particularly relevant with the new match dialog, which contains individual rule counts for each team. 

<img width="414" alt="image" src="https://github.com/brenapp/referee.fyi/assets/8839926/eb083369-4d17-4c25-8518-2d5c520fd400">

One approach here is to still show the practice violations, but not count it in the rule summary section of the UI

**Comment by brenapp** [comment]
This has precedence already, as currently the rule summary only shows for Minor and Major violations, we could skip practice matches here. 

But I worry that would be unintuitive to the user, and stray too far towards being prescriptive. I think the best approach is to represent what they have been entered, present Head Referees with the right information at the right time, and allow them to consider violations in practice matches in context.
