### ISSUE TITLE
Associated rules using VIQRC rules in VRC events

### ISSUE THREAD

**Issue by MiniMitre** [brenapp/referee.fyi#46]
The 'associated rules' section will allow the user to input a VIQRC rule in a VRC match.

Fix is to either reset associated rules when a new event is selected, or to differentiate between IQ and VRC rules, and only display recent rules for the current competition type

**Comment by MiniMitre** [comment]
Also, noticed this when attempting to implement editing violations. At the moment, the only information we store about the rule violated is the 2-4 character rule 'number' e.g. G1 or SG11. We do not store whether it was a VRC or VIQRC rule that was violated.

So this bug needs to be fixed before we can implement editing of violations

**Comment by brenapp** [comment]
Ooh good spot. You'll likely want to look at modifications for `useRecentRules.` If you pass the event, we can differentiate by program.

See reference file: https://github.com/brenapp/referee.fyi/blob/f3b0cfbcb96a9e08dd2a94a5d932e3bfcd4f6bea/src/utils/hooks/history.ts
