### ISSUE TITLE
Suggestion: Allow user to submit violation without match.

### ISSUE THREAD

**Issue by MiniMitre** [brenapp/referee.fyi#9]
Some violations (e.g. G1 and S2) do not require a match to be associated with them.

Also, the user may need to record a violation for a team but is not sure of the match number.

Suggestion is to allow the option to submit without a match attached to it (perhaps with an 'are you sure you want to submit without recording a match number' pop up to confirm)

**Comment by brenapp** [comment]
I think that makes a lot of sense yeah. I was originally requiring either a match or a team. I think this dovetails nicely with your suggestion in #10. 

I think the data model we want to support is:
1. The user can specify a match or not
2. If they specify a match, they must pick a team that is in that match.
3. If they do not specify a match, they can pick any team in the event

I don't think we should support selecting a match and a team that is not in the match. In the case where that might be applicable, I think it's probably a G1 type issue, and the log should be attached to that team without a match.

**Comment by brenapp** [comment]
Addressed in #24
