### ISSUE TITLE
Page jumps from "Matches" to "Teams" tab when scrolling on mobile

### ISSUE THREAD

**Issue by Battlesquid** [brenapp/referee.fyi#93]
As suggested by the title, I've run into an issue where scrolling on the "Matches" tab causes the page to navigate to the "Teams" tab. Attempting to navigate back to the Matches tab and scrolling will repeat this action a few times before stopping. 

This issue doesn't occur often, so I'm currently unsure of how to reproduce it.

**Comment by brenapp** [comment]
Ah yeah, I suspect this is to due to the implementation of swiping between tabs. It's a nice feature, and something I use, but proving to be a lot of trouble. I'm thinking about disabling it until I can spend some time to rework it.
